server:
  port: 8081

spring:
  application:
    name: demo
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: 'true'

logging:
  level:
    root: INFO
    com.ejemplo.microservicio: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
  file:
    path: logs
    name: app.log

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html